#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef WPPSDK_SWIFT_H
#define WPPSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import PassKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WPPSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSData;
SWIFT_CLASS("_TtC6WPPSDK14CompletionData")
@interface CompletionData : NSObject
@property (nonatomic, readonly, copy) NSArray<NSData *> * _Nonnull certificates;
@property (nonatomic, readonly, copy) NSData * _Nonnull nonce;
@property (nonatomic, readonly, copy) NSData * _Nonnull nonceSignature;
- (nonnull instancetype)initWithCertificates:(NSArray<NSData *> * _Nonnull)certificates nonce:(NSData * _Nonnull)nonce nonceSignature:(NSData * _Nonnull)nonceSignature OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSString;
@class WPPInitResponse;
@class WPPMeaEncryptedCardData;
@class WPPEncryptedCardData;
/// Represents a card that has been cached for use in the Wallet Extension.
/// Cache this data after a successful <code>startProvisioning</code> call in your main app.
SWIFT_CLASS("_TtC6WPPSDK13WPPCachedCard")
@interface WPPCachedCard : NSObject
/// Unique identifier for this card (e.g., your internal card ID)
@property (nonatomic, readonly, copy) NSString * _Nonnull cardIdentifier;
/// Display name shown in Apple Wallet (e.g., “Visa •••• 1234”)
@property (nonatomic, readonly, copy) NSString * _Nonnull displayName;
/// Last 4 digits of the card number
@property (nonatomic, readonly, copy) NSString * _Nonnull lastFourDigits;
/// Card art image data (PNG recommended, 1536×969 pixels for best quality)
@property (nonatomic, readonly, copy) NSData * _Nullable cardArtData;
/// The tokenization receipt - required for completing provisioning.
/// NOTE: This receipt expires quickly (typically 15-30 minutes).
/// For reliable extension provisioning, use prepareCardForExtension().
@property (nonatomic, readonly, copy) NSString * _Nonnull tokenizationReceipt;
/// Primary account identifier from the tokenization response
@property (nonatomic, readonly, copy) NSString * _Nullable primaryAccountIdentifier;
/// Cardholder name
@property (nonatomic, readonly, copy) NSString * _Nullable cardholderName;
/// Payment network (e.g., “Visa”, “Mastercard”)
@property (nonatomic, readonly, copy) NSString * _Nullable paymentNetwork;
/// Timestamp when this cached data expires (Unix timestamp)
@property (nonatomic, readonly) NSTimeInterval expiryTimestamp;
/// Encrypted card data in bank/Wibmo format (DEPRECATED).
/// Use <code>meaEncryptedCardData</code> instead for extension provisioning.
@property (nonatomic, readonly, copy) NSData * _Nullable encryptedCardData SWIFT_DEPRECATED_MSG("Use meaEncryptedCardData instead");
/// Pre-processed encrypted card data for extension provisioning.
/// This data has been converted via the Wibmo API and is ready for use in extensions.
/// Use <code>WibmoPushProvisionSDK.prepareCardForExtension()</code> to get this data.
@property (nonatomic, readonly, copy) NSData * _Nullable meaEncryptedCardData;
/// Whether this cached card data has expired
@property (nonatomic, readonly) BOOL isExpired;
/// Creates a new cached card from a provisioning response with pre-processed data.
/// \param cardIdentifier Your unique identifier for this card
///
/// \param displayName Display name for the card
///
/// \param response The response from <code>startProvisioning</code>
///
/// \param meaEncryptedCardData Pre-processed encrypted data from <code>prepareCardForExtension()</code>
///
/// \param cardArtData Optional card art image data
///
/// \param validityDuration How long this cache should be valid (default: 30 days for card data)
///
- (nonnull instancetype)initWithCardIdentifier:(NSString * _Nonnull)cardIdentifier displayName:(NSString * _Nonnull)displayName response:(WPPInitResponse * _Nonnull)response meaEncryptedCardData:(WPPMeaEncryptedCardData * _Nullable)meaEncryptedCardData cardArtData:(NSData * _Nullable)cardArtData validityDuration:(NSTimeInterval)validityDuration OBJC_DESIGNATED_INITIALIZER;
/// Creates a new cached card from a provisioning response (DEPRECATED).
/// Use the initializer with <code>meaEncryptedCardData</code> instead.
- (nonnull instancetype)initWithCardIdentifier:(NSString * _Nonnull)cardIdentifier displayName:(NSString * _Nonnull)displayName response:(WPPInitResponse * _Nonnull)response encryptedCardData:(WPPEncryptedCardData * _Nullable)encryptedCardData cardArtData:(NSData * _Nullable)cardArtData validityDuration:(NSTimeInterval)validityDuration OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("Use init with meaEncryptedCardData instead");
/// Creates a cached card with explicit values.
- (nonnull instancetype)initWithCardIdentifier:(NSString * _Nonnull)cardIdentifier displayName:(NSString * _Nonnull)displayName lastFourDigits:(NSString * _Nonnull)lastFourDigits cardArtData:(NSData * _Nullable)cardArtData tokenizationReceipt:(NSString * _Nonnull)tokenizationReceipt primaryAccountIdentifier:(NSString * _Nullable)primaryAccountIdentifier cardholderName:(NSString * _Nullable)cardholderName paymentNetwork:(NSString * _Nullable)paymentNetwork expiryTimestamp:(NSTimeInterval)expiryTimestamp meaEncryptedCardData:(NSData * _Nullable)meaEncryptedCardData OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6WPPSDK20WPPEncryptedCardData")
@interface WPPEncryptedCardData : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull encryptedData;
@property (nonatomic, readonly, copy) NSString * _Nonnull publicKeyFingerprint;
@property (nonatomic, readonly, copy) NSString * _Nonnull encryptedKey;
@property (nonatomic, readonly, copy) NSString * _Nonnull iv;
- (nonnull instancetype)initWithEncryptedData:(NSString * _Nonnull)encryptedData publicKeyFingerprint:(NSString * _Nonnull)publicKeyFingerprint encryptedKey:(NSString * _Nonnull)encryptedKey iv:(NSString * _Nonnull)iv OBJC_DESIGNATED_INITIALIZER;
/// Serializes the encrypted card data to Data for storage in App Groups.
- (NSData * _Nullable)toData SWIFT_WARN_UNUSED_RESULT;
/// Creates an instance from serialized Data.
+ (WPPEncryptedCardData * _Nullable)fromData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Manages card data sharing between your main app and the Wallet provisioning extension.
/// <h2>Setup Requirements</h2>
/// <ol>
///   <li>
///     Enable App Groups capability in both your main app and extension targets
///   </li>
///   <li>
///     Create an App Group identifier (e.g., “group.com.yourcompany.yourapp”)
///   </li>
///   <li>
///     Add the same App Group to both targets in Xcode
///   </li>
/// </ol>
/// <h2>Usage in Main App</h2>
/// \code
/// let dataManager = WPPExtensionDataManager(appGroupId: "group.com.yourcompany.yourapp")
///
/// // After successful startProvisioning:
/// let cachedCard = WPPCachedCard(
///     cardIdentifier: "card-123",
///     displayName: "My Visa Card",
///     response: provisioningResponse,
///     cardArtData: cardImage.pngData()
/// )
/// try dataManager.cacheCard(cachedCard)
///
/// \endcode<h2>Usage in Extension</h2>
/// \code
/// let dataManager = WPPExtensionDataManager(appGroupId: "group.com.yourcompany.yourapp")
/// let availableCards = dataManager.getAvailableCards()
///
/// \endcode
SWIFT_CLASS("_TtC6WPPSDK23WPPExtensionDataManager")
@interface WPPExtensionDataManager : NSObject
/// Creates a new data manager for the specified App Group.
/// \param appGroupId The App Group identifier (e.g., “group.com.yourcompany.yourapp”)
///
- (nonnull instancetype)initWithAppGroupId:(NSString * _Nonnull)appGroupId OBJC_DESIGNATED_INITIALIZER;
/// Caches a card for use by the Wallet extension.
/// Call this after a successful <code>startProvisioning</code> in your main app.
/// \param card The card data to cache
///
///
/// throws:
/// Encoding errors if the card cannot be serialized
- (BOOL)cacheCard:(WPPCachedCard * _Nonnull)card error:(NSError * _Nullable * _Nullable)error;
/// Removes a cached card by its identifier.
/// \param cardIdentifier The unique identifier of the card to remove
///
- (void)removeCardWithCardIdentifier:(NSString * _Nonnull)cardIdentifier;
/// Removes cached cards matching the last 4 digits.
/// \param lastFourDigits The last 4 digits of the card to remove
///
- (void)removeCardWithLastFourDigits:(NSString * _Nonnull)lastFourDigits;
/// Removes all cached cards.
- (void)clearAllCards;
/// Returns all cached cards, including expired ones.
///
/// returns:
/// Array of all cached cards
- (NSArray<WPPCachedCard *> * _Nonnull)getAllCachedCards SWIFT_WARN_UNUSED_RESULT;
/// Returns only valid (non-expired) cached cards.
///
/// returns:
/// Array of valid cached cards
- (NSArray<WPPCachedCard *> * _Nonnull)getAvailableCards SWIFT_WARN_UNUSED_RESULT;
/// Returns cards that can be added to the wallet (not expired and not already in wallet).
///
/// returns:
/// Array of cards eligible for provisioning
- (NSArray<WPPCachedCard *> * _Nonnull)getProvisionableCards SWIFT_WARN_UNUSED_RESULT;
/// Retrieves a specific cached card by its identifier.
/// \param cardIdentifier The unique identifier of the card
///
///
/// returns:
/// The cached card if found and not expired, nil otherwise
- (WPPCachedCard * _Nullable)getCardWithCardIdentifier:(NSString * _Nonnull)cardIdentifier SWIFT_WARN_UNUSED_RESULT;
/// Removes all expired cards from the cache.
- (void)cleanupExpiredCards;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PKIssuerProvisioningExtensionStatus;
/// Helper class for Wallet Extension operations.
/// Use this class in your PKIssuerProvisioningExtensionHandler implementation.
SWIFT_CLASS("_TtC6WPPSDK18WPPExtensionHelper")
@interface WPPExtensionHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Configures the extension helper. Call this in your extension’s init().
/// \param configFileName SDK config file name (without .plist extension)
///
/// \param appGroupId App Group ID for shared storage
///
/// \param debugLogging Enable debug logging (default: false)
///
- (void)configureWithConfigFileName:(NSString * _Nonnull)configFileName appGroupId:(NSString * _Nonnull)appGroupId debugLogging:(BOOL)debugLogging;
/// Creates a PKIssuerProvisioningExtensionStatus based on cached cards.
/// Call this in your status() method.
/// \param requiresAuthentication Whether authentication is required before adding cards
///
///
/// returns:
/// Configured PKIssuerProvisioningExtensionStatus
- (PKIssuerProvisioningExtensionStatus * _Nonnull)getExtensionStatusWithRequiresAuthentication:(BOOL)requiresAuthentication SWIFT_WARN_UNUSED_RESULT;
@end

/// Result from initializing tokenization in a Wallet Extension.
/// Contains the configuration needed to create pass entries and the receipt for completing tokenization.
SWIFT_CLASS("_TtC6WPPSDK30WPPExtensionTokenizationResult")
@interface WPPExtensionTokenizationResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PKAddPaymentPassRequestConfiguration;
SWIFT_CLASS("_TtC6WPPSDK15WPPInitResponse")
@interface WPPInitResponse : NSObject
@property (nonatomic, readonly, strong) PKAddPaymentPassRequestConfiguration * _Nullable requestConfiguration;
/// The tokenization receipt. Required for completing provisioning.
/// Cache this value if you need to complete provisioning from an extension context.
@property (nonatomic, readonly, copy) NSString * _Nullable tokenizationReceipt;
@property (nonatomic, readonly) BOOL canAddToWallet;
@property (nonatomic, readonly, copy) NSString * _Nullable cardholderName;
@property (nonatomic, readonly, copy) NSString * _Nullable lastFourDigits;
@property (nonatomic, readonly, copy) NSString * _Nullable primaryAccountIdentifier;
@property (nonatomic, readonly) PKPaymentNetwork _Nullable paymentNetwork;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents pre-processed encrypted card data for extension provisioning.
/// This data has been converted via the Wibmo API and is ready for use in extensions.
SWIFT_CLASS("_TtC6WPPSDK23WPPMeaEncryptedCardData")
@interface WPPMeaEncryptedCardData : NSObject
/// Encrypted card data (processed format)
@property (nonatomic, readonly, copy) NSString * _Nonnull encryptedData;
/// Public key fingerprint (from original bank data)
@property (nonatomic, readonly, copy) NSString * _Nonnull publicKeyFingerprint;
/// Encrypted key (processed format)
@property (nonatomic, readonly, copy) NSString * _Nonnull encryptedKey;
/// Initialization vector (processed format)
@property (nonatomic, readonly, copy) NSString * _Nonnull iv;
/// Creates pre-processed encrypted card data.
/// \param encryptedData The encrypted card data
///
/// \param publicKeyFingerprint The public key fingerprint
///
/// \param encryptedKey The encrypted key
///
/// \param iv The initialization vector
///
- (nonnull instancetype)initWithEncryptedData:(NSString * _Nonnull)encryptedData publicKeyFingerprint:(NSString * _Nonnull)publicKeyFingerprint encryptedKey:(NSString * _Nonnull)encryptedKey iv:(NSString * _Nonnull)iv OBJC_DESIGNATED_INITIALIZER;
/// Serializes to Data for storage in App Groups.
- (NSData * _Nullable)toData SWIFT_WARN_UNUSED_RESULT;
/// Creates an instance from serialized Data.
+ (WPPMeaEncryptedCardData * _Nullable)fromData:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC6WPPSDK21WibmoPushProvisionSDK")
@interface WibmoPushProvisionSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
